[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/id_rsa

[loadbalancers]
lb-node-01 ansible_host=10.10.10.11
lb-node-02 ansible_host=10.10.10.12

[k8s_masters]
k8s-master-01 ansible_host=10.10.10.21
k8s-master-02 ansible_host=10.10.10.22
k8s-master-03 ansible_host=10.10.10.23

[k8s_workers]
k8s-worker-01 ansible_host=10.10.10.31
k8s-worker-02 ansible_host=10.10.10.32

[ceph_nodes]
ceph-node-01 ansible_host=10.10.10.41
ceph-node-02 ansible_host=10.10.10.42
ceph-node-03 ansible_host=10.10.10.43